initContainers:
  enabled: true
  vault_init_container_enabled: true

schema:
  enabled: true
  db_type: mongo

component: catalogue
appVersion: 2.0.2

service:
  type: ClusterIP
  port: 8080
  targetPort: 8080

ingress:
  enabled: false

