initContainers:
  enabled: false
component: frontend
appVersion: 2.0.5

service:
  type: ClusterIP
  port: 80
  targetPort: 80

ingress:
  enabled: true
  hostName: frontend-dev.psrikanth.online

resources:
  requests:
    memory: "256Mi"
    cpu: "200m"
  limits:
    memory: "512Mi"
    cpu: "400m"

