initContainers:
  enabled: true
  vault_init_container_enabled: true

component: payment
appVersion: 2.0.0

service:
  type: ClusterIP
  port: 8080
  targetPort: 8080

ingress:
  enabled: false

resources:
  requests:
    memory: "512Mi"
    cpu: "250m"
  limits:
    memory: "1024Mi"
    cpu: "500m"

