initContainers:
  enabled: true
  vault_init_container_enabled: true

schema:
  enabled: true
  db_type: mysql


component: shipping
appVersion: 2.0.5

service:
  type: ClusterIP
  port: 8080
  targetPort: 8080

ingress:
  enabled: false

resources:
  requests:
    memory: "2Gi"
    cpu: "1000m"
  limits:
    memory: "3Gi"
    cpu: "1500m"

